import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import { Header, Nav, Results } from "../components";
import requests from "../utils/requests";

const Home: NextPage = ({ results }: any) => {
  return (
    <>
      <Head>
        <title>Project Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={results} />
    </>
  );
};

export default Home;

export async function getServerSideProps(ctx: NextPageContext) {
  const genre = ctx.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
